import { Accordion, AccordionItem, Input, Switch, Divider } from "@heroui/react";
import { FaBuilding, FaCalendarAlt, FaUser } from "react-icons/fa";

interface CustomizeSidebarProps {
  // Header props
  headerTitle: string;
  institutionName: string;
  academicYear: string;
  generatedBy: string;
  onHeaderChange: (field: string, value: string) => void;

  // Info props (optional visibility controls)
  showClassInfo: boolean;
  showRoomInfo: boolean;
  showCourseInfo: boolean;
  showFacultyInfo: boolean;
  showProgramInfo: boolean;
  onInfoVisibilityChange: (field: string, value: boolean) => void;

  // Footer props
  preparedBy: string;
  verifiedBy: string;
  approvedBy: string;
  showSignatures: boolean;
  showReportInfo: boolean;
  onFooterChange: (field: string, value: string | boolean) => void;

  // Table props
  showStriped: boolean;
  showFooterSummary: boolean;
  onTableChange: (field: string, value: boolean) => void;
}

const CustomizeSidebar = ({
  headerTitle,
  institutionName,
  academicYear,
  generatedBy,
  onHeaderChange,
  showClassInfo,
  showRoomInfo,
  showCourseInfo,
  showFacultyInfo,
  showProgramInfo,
  onInfoVisibilityChange,
  preparedBy,
  verifiedBy,
  approvedBy,
  showSignatures,
  showReportInfo,
  onFooterChange,
  showStriped,
  showFooterSummary,
  onTableChange,
}: CustomizeSidebarProps) => {
  return (
    <div className="h-full overflow-y-auto">
      <div className="p-4 bg-zinc-50 dark:bg-zinc-800 rounded-lg sticky top-0 z-10 mb-4">
        <h2 className="text-lg font-semibold">Customize Report</h2>
        <p className="text-xs text-zinc-500 dark:text-zinc-400">Adjust report settings</p>
      </div>

      <Accordion 
        variant="splitted" 
        itemClasses={{ base: "shadow-none mb-2" }}
        defaultExpandedKeys={["header"]}
      >
        {/* Customize Header */}
        <AccordionItem 
          key="header"
          title="Customize Header" 
          startContent={<FaBuilding className="text-primary" />}
        >
          <div className="space-y-3 pb-2">
            <Input
              label="Report Title"
              labelPlacement="outside"
              placeholder="Enter report title"
              value={headerTitle}
              onChange={(e) => onHeaderChange('title', e.target.value)}
              size="sm"
              variant="bordered"
            />
            <Input
              label="Institution Name"
              labelPlacement="outside"
              placeholder="Enter institution name"
              value={institutionName}
              onChange={(e) => onHeaderChange('institutionName', e.target.value)}
              size="sm"
              variant="bordered"
            />
            <Input
              label="Academic Year"
              labelPlacement="outside"
              placeholder="e.g., 2024-2025"
              value={academicYear}
              onChange={(e) => onHeaderChange('academicYear', e.target.value)}
              size="sm"
              variant="bordered"
              startContent={<FaCalendarAlt className="text-zinc-400" />}
            />
            <Input
              label="Generated By"
              labelPlacement="outside"
              placeholder="Enter your name"
              value={generatedBy}
              onChange={(e) => onHeaderChange('generatedBy', e.target.value)}
              size="sm"
              variant="bordered"
              startContent={<FaUser className="text-zinc-400" />}
            />
          </div>
        </AccordionItem>

        {/* Customize Info Section */}
        <AccordionItem 
          key="info"
          title="Customize Info Section"
        >
          <div className="space-y-3 pb-2">
            <p className="text-xs text-zinc-500 dark:text-zinc-400 mb-2">
              Toggle visibility of information fields
            </p>
            <Divider />
            <div className="flex justify-between items-center">
              <span className="text-sm">Show Class Info</span>
              <Switch
                size="sm"
                isSelected={showClassInfo}
                onValueChange={(value) => onInfoVisibilityChange('showClassInfo', value)}
              />
            </div>
            <div className="flex justify-between items-center">
              <span className="text-sm">Show Room Info</span>
              <Switch
                size="sm"
                isSelected={showRoomInfo}
                onValueChange={(value) => onInfoVisibilityChange('showRoomInfo', value)}
              />
            </div>
            <div className="flex justify-between items-center">
              <span className="text-sm">Show Course Info</span>
              <Switch
                size="sm"
                isSelected={showCourseInfo}
                onValueChange={(value) => onInfoVisibilityChange('showCourseInfo', value)}
              />
            </div>
            <div className="flex justify-between items-center">
              <span className="text-sm">Show Faculty Info</span>
              <Switch
                size="sm"
                isSelected={showFacultyInfo}
                onValueChange={(value) => onInfoVisibilityChange('showFacultyInfo', value)}
              />
            </div>
            <div className="flex justify-between items-center">
              <span className="text-sm">Show Program Info</span>
              <Switch
                size="sm"
                isSelected={showProgramInfo}
                onValueChange={(value) => onInfoVisibilityChange('showProgramInfo', value)}
              />
            </div>
          </div>
        </AccordionItem>

        {/* Customize Item List/Table */}
        <AccordionItem 
          key="itemlist"
          title="Customize Table"
        >
          <div className="space-y-3 pb-2">
            <p className="text-xs text-zinc-500 dark:text-zinc-400 mb-2">
              Table display settings
            </p>
            <Divider />
            <div className="flex justify-between items-center">
              <span className="text-sm">Striped Rows</span>
              <Switch
                size="sm"
                isSelected={showStriped}
                onValueChange={(value) => onTableChange('showStriped', value)}
              />
            </div>
            <div className="flex justify-between items-center">
              <span className="text-sm">Show Footer Summary</span>
              <Switch
                size="sm"
                isSelected={showFooterSummary}
                onValueChange={(value) => onTableChange('showFooterSummary', value)}
              />
            </div>
            <Divider />
            <p className="text-xs text-zinc-500 dark:text-zinc-400 italic">
              Click on table headers to customize column labels and widths
            </p>
          </div>
        </AccordionItem>

        {/* Customize Footer */}
        <AccordionItem 
          key="footer"
          title="Customize Footer"
        >
          <div className="space-y-3 pb-2">
            <div className="flex justify-between items-center mb-3">
              <span className="text-sm font-medium">Show Signatures</span>
              <Switch
                size="sm"
                isSelected={showSignatures}
                onValueChange={(value) => onFooterChange('showSignatures', value)}
              />
            </div>
            
            {showSignatures && (
              <>
                <Divider />
                <Input
                  label="Prepared By"
                  labelPlacement="outside"
                  placeholder="Enter name/title"
                  value={preparedBy}
                  onChange={(e) => onFooterChange('preparedBy', e.target.value)}
                  size="sm"
                  variant="bordered"
                />
                <Input
                  label="Verified By"
                  labelPlacement="outside"
                  placeholder="Enter name/title"
                  value={verifiedBy}
                  onChange={(e) => onFooterChange('verifiedBy', e.target.value)}
                  size="sm"
                  variant="bordered"
                />
                <Input
                  label="Approved By"
                  labelPlacement="outside"
                  placeholder="Enter name/title"
                  value={approvedBy}
                  onChange={(e) => onFooterChange('approvedBy', e.target.value)}
                  size="sm"
                  variant="bordered"
                />
              </>
            )}
            
            <Divider />
            <div className="flex justify-between items-center">
              <span className="text-sm">Show Report Info</span>
              <Switch
                size="sm"
                isSelected={showReportInfo}
                onValueChange={(value) => onFooterChange('showReportInfo', value)}
              />
            </div>
          </div>
        </AccordionItem>
      </Accordion>
    </div>
  );
};

export default CustomizeSidebar;