import { useReportCustomizationStore } from "@/stores/useReportStore";

const CustomizeHeader = () => {
  const { header } = useReportCustomizationStore();

  return (
    <div className="text-center mb-6 border-b-2 border-zinc-300 dark:border-zinc-700 pb-4">
      <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100 mb-2">
        {header.title}
      </h1>
      <div className="flex justify-between items-center text-sm text-zinc-600 dark:text-zinc-400">
        <div>
          <p><strong>Institution:</strong> {header.institutionName}</p>
          <p><strong>Academic Year:</strong> {header.academicYear}</p>
        </div>
        <div className="text-right">
          <p><strong>Report Date:</strong> {new Date().toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
          })}</p>
          <p><strong>Generated By:</strong> {header.generatedBy}</p>
        </div>
      </div>
    </div>
  );
};

export default CustomizeHeader;